version: '3.3'
services:
  mongo:
    image: mongo:5.0.8
  tester:
    image: mongo-perf:latest
    entrypoint:
    - bash
    - -c
    - "sleep 3 && python3 benchrun.py --host mongo -f /workdir/testcases/query_unique_idx.js -t 4 --trialTime 20"